### ISSUE TITLE
Polygon Labeler Crash with Mercator or Orthographic projection

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1199]
When using a map projection of Mercator or Orthographic (possibly others as well) and labeling polygons there is a small bug that I have been trying to squash all weekend. I believe it is because when the reprojection of the polygons occurs there are some inherent values of NaN for x or y or both. When the labeler tries to determine the centroid of the said features it results in an exception.

### Steps to reproduce
1. Add countries layer to a WGS84 map and label the countries
2. Change the map projection to Orthographic
3. An exception will occur with the first polygon feature that has a NaN vertex.

DotSpatial version: 2.0
I have narrowed it down to these sequence of events. I have been trying to tweak routines in MapLabelLayer so that I can skip those features which include a NaN vertex. I wanted to avoid tweaking the Data namespace. I have been adjusting the DrawFeatures routines to filter out any features with NaN coordinates but every attempt fires off GetPolygon and the exception is thrown. Are there any other suggestions I may try? 

```
System.ArgumentException: points must form a closed linestring

   at NetTopologySuite.Geometries.LinearRing.ValidateConstruction()

   at NetTopologySuite.Geometries.GeometryFactory.CreateLinearRing(Coordinate[] coordinates)

   at DotSpatial.Data.FeatureSet.GetPolygon(Int32 index) in C:\Users\AGP\Documents\GitHub\DotSpatialX\Source\DotSpatial.Data\FeatureSet.cs:line 1815
 
   at DotSpatial.Data.PolygonShapefile.GetFeature(Int32 index) in C:\Users\AGP\Documents\GitHub\DotSpatialX\Source\DotSpatial.Data\PolygonShapefile.cs:line 143
      
   at DotSpatial.Controls.MapLabelLayer.DrawFeatures(MapArgs e, IEnumerable`1 features) in C:\Users\AGP\Documents\GitHub\DotSpatialX\Source\DotSpatial.Controls\MapLabelLayer.cs:line 0
      
   at DotSpatial.Controls.MapLabelLayer.DrawFeatures(MapArgs args, List`1 features, List`1 clipRectangles, Boolean useChunks) in C:\Users\AGP\Documents\GitHub\DotSpatialX\Source\DotSpatial.Controls\MapLabelLayer.cs:line 389
      
   at DotSpatial.Controls.MapLabelLayer.DrawRegions(MapArgs args, List`1 regions, Boolean selected) in C:\Users\AGP\Documents\GitHub\DotSpatialX\Source\DotSpatial.Controls\MapLabelLayer.cs:line 434

```

**Comment by sindizzy** [comment]
@jany-tenaj @MatthiasSchilder heer is my solution for this issue. I didn't see any feature property that would work in this case so I made a function for it. Can you please review and let me know if I can save on processing?

```
        public virtual void DrawFeatures(MapArgs args, List<int> features, List<Rectangle> clipRectangles, bool useChunks)
        {
            if (useChunks == false)
            {
                DrawFeatures(args, features);
                return;
            }

            int count = features.Count;
            int numChunks = (int)Math.Ceiling(count / (double)ChunkSize);

            for (int chunk = 0; chunk < numChunks; chunk++)
            {
                int numFeatures = ChunkSize;
                if (chunk == numChunks - 1) numFeatures = features.Count - (chunk * ChunkSize);

                // without checking vertices for NaN this will casuse some issues with certain map projections like
                // Mercator and Orthographic.
                // DrawFeatures(args, features.GetRange(chunk * ChunkSize, numFeatures));

                // here we will test to see if any of the vertices have a NaN value and if so then we will remove
                // that feature index from the list. it is essentially a filter so the labeler has a complete set
                // of vertices to place a label. we first cache the indexes with invalid vertices and then after
                // that we will remove them from the master list. I suppose there might already be a feture property
                // that contains the vertice validity but dont know the codebase well enough to make that determination.
                // it would save computation if it were available before this routine was reached.
                var featsValid = features.GetRange(chunk * ChunkSize, numFeatures);
                var invalidList = new List<int>();
                foreach (int fid in featsValid)
                {
                 var isValidVtcs = GetFeatureVerticesAreValid(FeatureSet.ShapeIndices[fid].Parts);
                 if (!isValidVtcs) invalidList.Add(fid);
                }

                foreach (int invfid in invalidList)
                {
                 featsValid.Remove(invfid);
                }

                DrawFeatures(args, featsValid);

                if (numChunks > 0 && chunk < numChunks - 1)
                {
                    OnBufferChanged(clipRectangles);
                    Application.DoEvents();
                }
            }
        }

        private static bool GetFeatureVerticesAreValid(List<PartRange> prts)
        {
          // cycle through all parts
          foreach (PartRange prt in prts)
          {
            // we only need to find the first vertex that has a NaN value in x or y. if we find it then
            // the result is that the part range is not valid.
            var idxInvalid = prt.ToList().FindIndex(v => double.IsNaN(v.X) || double.IsNaN(v.Y));
            if (idxInvalid != -1)
              return false;
          }

          // if we get to this line then all vertices are valid so the part range is valid
          return true;
        }

```

**Comment by jany-tenaj** [comment]
I'd say if you have NaN values this sounds as if your data should not be converted from your source coordinate system into your destination coordinate system, because your data is not able to handle this. Otherwise I'd say you should rather fix your data after converting so it doesn't contain any NaN values instead of changing the code. 

I don't think changing the drawing functions would be the right way to go. This adds code that has to be run whenever the screen is updated even for those cases where the data is not corrupted.

**Comment by sindizzy** [comment]
The whole point of reprojection is that you can take multiple data sources with various coordinate systems and add them to a single map. The case here is that the data is not corrupted, it is valid. In fact it is a polygon shapefile of all the world's countries in WGS84. The source data does not have any NaN values. Now when I add this featureset to a map that is on an Orthographic projection the data has to get reprojected. This is where the NaN values get introduced by dotspatial.

The features themselves get drawn fine. It is the labeler that breaks on the re-projected vertices. I cant remove the NaN vertices because they can become valid if re-projected again. This is also loosely connected to the multiple reprojection defect that I posted about here https://github.com/DotSpatial/DotSpatial/issues/1104. I have a recommended solution for that one too.

In working with GIS and providing the user/developer a reprojection engine it is my belief that you cant restrict the map projection to the coord system of the data.  Nor can you restrict the changing of the map projection multiple times in the same session.

I think dotspatial is great and have switched most of my GIS work to this framework. Awesome work.

**Comment by sindizzy** [comment]
Oh yes I have seen that warning message. However, in my experience and data sources that I use, that has not been a problem. The features are drawn where they should be and the labeling also works fairly well. But let me be a bit more clear on the current issue. The features are being drawn with no problems. **It is the labeler that crashes**. The code that I have tweaked is in DotSpatial.Controls.MapLabelLayer and although the function is called DrawFeatures I don't think its function is to draw the spatial features themselves but rather the **labels** for the features. In this function the code has to get the polygon so that it can ascertain where to place the label. When it tries to create the LinearRing with NaNs that's where it bombs. I guess the labels themselves could be called "features". I would have rather called that function DrawFeatureLabels. One other thing that kind of confused me also was the calling of feature indexes  as "features". At first I thought it was the feature objects but in fact they were integers referencing feature indexes (List<int> features). I would have rather called them List<int> featIndexes.

Anyway, I have modified the code that labels the polygons and also introduced a new routine that when reprojecting does not use the vertices in memory. Rather it reloads the original featureset and then reprojects it. Obviously this will not work with in-memory featuresets or drawings but for my work I mostly use shapefiles on the disk. It essentially guarantees that any reprojection is occurring on the original vertices and not the re-re-re-projected vertices which have the potential to lose their original values. If you check my post about the reprojection issue you can see that when projecting to NPS any point that touches the north pole will get a x=0, y=90 vertex. If you change back to WGS84 that vertex has already lost its original value and you can't get it back with the current DS framework.

I have screen captured my code in action with the WorldFromSpace (Orthographic) map projection 
https://www.screencast.com/t/MvzNcHrBszm
This demos the two issues I have encountered with a custom solution: 1) multiple reprojections in the same session lose original vertex values and 2) the labeler will crash when vertices are NaN which is a direct result of reprojection.
