### ISSUE TITLE
Opening Esri \sta.adf raster file

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#175]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/181)**

**[jsp5568](http://www.codeplex.com/site/users/view/jsp5568)** wrote 2010-12-02 at 17:55
If you refer to my discussion post "Converting Esri grid/ascii grid to .bgd" I am having issues opening an esri raster file. I have tried opening it using the raster.open(name\sta.adf) method and receive a file not supported exception and have
 tested open it using the Demomap.exe (Downloaded Nov 28 2010) and I receive a unhandled exception error (see below) attached is an example of the type of files I am trying to open

Thanks 

J. 

See the end of this message for details on invoking 

just-in-time (JIT) debugging instead of this dialog box. 

************** Exception Text ************** 

System.ApplicationException: The specified file type is not supported. 

at DotSpatial.Data.DataManager.OpenFile(String fileName, Boolean inRam, IProgressHandler progressHandler) in C:\Dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\DataManager.cs:line 427

at DotSpatial.Data.Forms.DataManagerExt.OpenFile(IDataManager self) in C:\Dev\DotSpatial\DotSpatial.Data\DotSpatial.Data.Forms\DataManagerExt.cs:line 106

at DotSpatial.Controls.Map.AddLayer() in C:\Dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\Map.cs:line 623

at DotSpatial.Controls.Map.DotSpatial.Controls.IBasicMap.AddLayer() in C:\Dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\Map.cs:line 613

at DotSpatial.Controls.SpatialToolStrip.cmdAddData_Click(Object sender, EventArgs e) in C:\Dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\SpatialToolStrip.cs:line 481

at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e) 

at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e) 

at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e) 

at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e) 

at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)

at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)

at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea) 

at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

at System.Windows.Forms.Control.WndProc(Message& m) 

at System.Windows.Forms.ScrollableControl.WndProc(Message& m) 

at System.Windows.Forms.ToolStrip.WndProc(Message& m) 

at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) 

at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) 

at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies ************** 

mscorlib

<pre><code>Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)</code></pre>
<h2>CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll</h2>
DemoMap

<pre><code>Assembly Version: 1.0.0.40019
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DemoMap.exe</h2>
System.Windows.Forms

<pre><code>Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.1 built by: RTMRel</code></pre>
<h2>CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll</h2>
System.Drawing

<pre><code>Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.1 built by: RTMRel</code></pre>
<h2>CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll</h2>
System

<pre><code>Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.1 built by: RTMRel</code></pre>
<h2>CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll</h2>
DotSpatial.Controls

<pre><code>Assembly Version: 1.0.0.40017
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Controls.DLL</h2>
DotSpatial.Symbology

<pre><code>Assembly Version: 1.0.0.40011
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Symbology.DLL</h2>
DotSpatial.Topology

<pre><code>Assembly Version: 1.0.0.40007
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Topology.DLL</h2>
DotSpatial.Data

<pre><code>Assembly Version: 1.0.0.40009
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Data.DLL</h2>
DotSpatial.Data.Forms

<pre><code>Assembly Version: 1.0.0.40011
Win32 Version: 1.0.0.40011</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Data.Forms.DLL</h2>
DotSpatial.Symbology.Forms

<pre><code>Assembly Version: 1.0.0.40014
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Symbology.Forms.DLL</h2>
System.Core

<pre><code>Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.1 built by: RTMRel</code></pre>
<h2>CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll</h2>
DotSpatial.Projections

<pre><code>Assembly Version: 1.0.0.40006
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Projections.DLL</h2>
DotSpatial.Serialization

<pre><code>Assembly Version: 1.0.0.40006
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Serialization.DLL</h2>
System.Xml

<pre><code>Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.1 built by: RTMRel</code></pre>
<h2>CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll</h2>
DotSpatial.Modeling.Forms

<pre><code>Assembly Version: 1.0.0.40016
Win32 Version: 1.0.0.0</code></pre>
<h2>CodeBase: file:///D:/downloads/mwReleaseNov282010/x86/DotSpatial.Modeling.Forms.DLL</h2>
************** JIT Debugging ************** 

To enable just-in-time (JIT) debugging, the .config file for this 

application or computer (machine.config) must have the 

jitDebugging value set in the system.windows.forms section. 

The application must also be compiled with debugging 

enabled. 

For example: 

<configuration>

<pre><code><system.windows.forms jitDebugging="true" /></code></pre>
</configuration> 

When JIT debugging is enabled, any unhandled exception 

will be sent to the JIT debugger registered on the computer 

rather than be handled by this dialog box.

**[Shade1974](http://www.codeplex.com/site/users/view/Shade1974)** wrote 2010-12-16 at 05:32
I have investigated this, and the good news is I was able to fix a bug related to short raster ESRI grids, and can open the sample data esri grid from the MapWindow 4 sample data repository. The bad news is that all variants of GDAL that I have turned
 up their nose at your particular type of ESRI grid. I have no explanation for it other than you must be using a grid version that is incompatible with GDAL. This might happen if you were using an unconventional data type or possibly something so new fangled
 from ArcGIS that GDAL hasn't caught up with it? It might even be the C# bindings that are to blame, I'm not sure. The old version of Basins that I had lying around on my machine just locked up when I tried to open it, so that wasn't a lot of help. Also, I
 don't have an ESRI license to use from home, so I can't even ensure this is valid, but presuming it is, the next step might be to try to hunt down the GDAL people and see if this type of grid needs special handling for some reason, or is simply not supported
 at all. It's a mystery.

Ted

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2011-02-28 at 16:49
I have the same problem with adf files from NHDPlus which both Mapwindow 4 and openEV from FWTools could read. I have not been able to figure out a solution to this.

**Comment by mogikanin** [comment]
Not reproduced.
