### ISSUE TITLE
Null reference exception while deleting a layer

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#215]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/221)**

**[mailvamsee](http://www.codeplex.com/site/users/view/mailvamsee)** wrote 2011-01-27 at 20:04
I am working on an application using the dotspatial dll's to retreive and display an image from a web service. This image is saved to the drive along with the prj information and then added as a layer to the map and legend. When the user pans or zooms
 the previously added image layer is removed and a new layer is added. 

Everything was working fine in the previous build, but in the latest build - 12/15/2010, Map.Layers.Remove(IMapLayer) is throwing an error. The stack trace or the error is below:

at DotSpatial.Data.InRamImageData.OnBoundsChanged(IRasterBounds bounds) in c:\Dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\InRamImageData.cs:line 457

at DotSpatial.Data.RasterBoundDataSet.set_Bounds(IRasterBounds value) in c:\Dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\RasterBoundDataSet.cs:line 57

at DotSpatial.Data.RasterBoundDataSet.set_Bounds(IRasterBounds value) in c:\Dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\RasterBoundDataSet.cs:line 51

at DotSpatial.Data.ImageData.Dispose(Boolean disposeManagedResources) in c:\Dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\ImageData.cs:line 538

at DotSpatial.Data.DisposeBase.Dispose() in c:\Dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\DisposeBase.cs:line 55

at DotSpatial.Symbology.Layer.Dispose(Boolean disposeManagedResources) in c:\Dev\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology\Layer.cs:line 865

at DotSpatial.Symbology.ImageLayer.Dispose(Boolean disposeManagedResources) in c:\Dev\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology\ImageLayer.cs:line 173

at DotSpatial.Symbology.Layer.Dispose() in c:\Dev\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology\Layer.cs:line 784

at DotSpatial.Symbology.LayerEventList<code>1.OnExclude(T item) in c:\Dev\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology\LayerEventList.cs:line 220

at DotSpatial.Symbology.LayerCollection.OnExclude(ILayer item) in c:\Dev\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology\LayerCollection.cs:line 100

at DotSpatial.Serialization.BaseList</code>1.RemoveAt(Int32 index) in c:\Dev\DotSpatial\DotSpatial.Serialization\DotSpatial.Serialization\BaseList.cs:line 160

at 

This is my code for adding the layer, which I am trying to remove: 

IImageData imageData = new ImageData(string.Format("{0}\{1}.jpg", Properties.Settings.Default.ApplicationFilesLocation, fileName));

IMapImageLayer layer = new MapImageLayer(imageData); 

GlobalVariable.g_Map.Layers.Add(layer); 

layer.LegendText = layerName;

**Comment by mogikanin** [comment]
Not reproduced
