### ISSUE TITLE
Add points to existing shapefile error

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#271]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/278)**

**[Tevaganthan](http://www.codeplex.com/site/users/view/Tevaganthan)** wrote 2011-04-02 at 01:29
In the following code I have an error in Map1.ResetBuffer() function. The following is the error message. "Index was outside the bounds of the array."

If e.Button = MouseButtons.Left Then

<pre><code>                If (pointmouseClick) Then

                    'This method is used to convert the screen cordinate to map coordinate
                    'e.location is the mouse click point on the map control
                    Dim coord As Coordinate = Map1.PixelToProj(e.Location)
                    'Create a new point
                    'Input parameter is clicked point coordinate
                    Dim point As New DotSpatial.Topology.Point(coord)
                    'Add the point into the Point Feature
                    'assigning the point feature to IFeature because via it only we can set the attributes.
                    Dim currentFeature As IFeature = ExistingpointF.AddFeature(point)
                    'increase the point id
                    pointID = pointID + 1
                    'set the ID attribute
                    currentFeature.DataRow("ID") = 999 'to test new point ID
                    'refresh the map
                    ExistingpointF.InitializeVertices()
                    Map1.ResetBuffer()
                End If
            Else
                Map1.Cursor = Cursors.Default
                pointmouseClick = False
            End If
</code></pre>
ExistingPointF variable is the FeatureSet of the existing point shapefile. 

The detailed exception message is: 

at DotSpatial.Controls.MapPointLayer.DrawFeatures(MapArgs e, IEnumerable<code>1 indices) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapPointLayer.cs:line 478

at DotSpatial.Controls.MapPointLayer.DrawFeatures(MapArgs args, List</code>1 indices, List<code>1 clipRectangles, Boolean useChunks) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapPointLayer.cs:line 219

at DotSpatial.Controls.MapPointLayer.DrawRegions(MapArgs args, List</code>1 regions) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapPointLayer.cs:line 286

at DotSpatial.Controls.MapFrame.Initialize(List`1 regions) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrame.cs:line 323

at DotSpatial.Controls.MapFrame.Initialize() in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrame.cs:line 386

at DotSpatial.Controls.MapFrame.ResetBuffer() in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrame.cs:line 291

at DotSpatial.Controls.Map.ResetBuffer() in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\Map.cs:line 699

at Tutorial4Demo.Form1.Map1_MouseDown(Object sender, MouseEventArgs e) in C:\Users\Teva\Desktop\2011 Spring\Programming for GIS\Teva\HW06\Version2

**Comment by mogikanin** [comment]
Not reproduced.
