### ISSUE TITLE
Toolbox error - spaces in filename

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#273]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/280)**

**[bogusman](http://www.codeplex.com/site/users/view/bogusman)** wrote 2011-04-12 at 01:46
Hope this is the right place for this. Have been working with the example in the Getting Started Guide and have received the following error:

System.Xml.XmlException was unhandled by user code 

Message=An error occurred while parsing EntityName. Line 6, position 70. 

Source=System.Xml 

LineNumber=6 

LinePosition=70 

SourceUri=file:///C:/Users/seank/AppData/Local/SantaRosaUtilities/ToolManagerSettings.xml

StackTrace:

<pre><code>   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, Int32 lineNo, Int32 linePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at DotSpatial.Controls.ToolManager.LoadSettings() in c:\Dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\ToolManager.cs:line 193
   at DotSpatial.Controls.ToolManager.RefreshTree() in c:\Dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\ToolManager.cs:line 290
   at DotSpatial.Controls.ToolManager.OnCreateControl() in c:\Dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\ToolManager.cs:line 79
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)</code></pre>
InnerException: 

The error is being caused by the spaces in the ToolManagerSettings.xml file: 

<Path Value ="C:\Users\seank\Prototype Programs\Proto1\Proto1\bin\Debug\Tools"></Path>

Deleting the settings file and rerunning the project from a folder w/o spaces, it works as expected.

Bo

**Comment by mogikanin** [comment]
Not actual
