### ISSUE TITLE
FalseEasting/FalseNorthing not working

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#278]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/285)**

**[dragandm](http://www.codeplex.com/site/users/view/dragandm)** wrote 2011-04-22 at 02:52
When using FalseEasting and FalseNorthing to move MapImageLayer type of layer in regard to other layers on a map, things work fine with small images, but not with larger ones, that are shown using triangularization and GDAL library I guess.

**[dragandm](http://www.codeplex.com/site/users/view/dragandm)** wrote 2011-04-22 at 13:12
Also excepion is thrown when trying to change FalseEasting (or northing) value in ProjectionString of large image layer and applying changes using Projection item in context menu of Legend control (available when right-clicking MapFrame item in Legend
 control).

Again, all of these steps work fine with images that are not triangularized.

System.NullReferenceException was unhandled

Message=Object reference not set to an instance of an object.

Source=DotSpatial.Controls

StackTrace:

<pre><code>   at DotSpatial.Controls.MapImageLayer.DrawWindows(MapArgs args, IList`1 regions, IList`1 clipRectangles) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapImageLayer.cs:line 227
   at DotSpatial.Controls.MapImageLayer.DrawRegions(MapArgs args, List`1 regions) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapImageLayer.cs:line 116
   at DotSpatial.Controls.MapFrame.Initialize(List`1 regions) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrame.cs:line 324
   at DotSpatial.Controls.MapFrame.Initialize() in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrame.cs:line 387
   at DotSpatial.Controls.MapFrame.Invalidate() in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrame.cs:line 531
   at DotSpatial.Controls.MapFrameProjectionDialog.ApplyChanges() in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrameProjectionDialog.cs:line 94
   at DotSpatial.Controls.MapFrameProjectionDialog.btnApply_Click(Object sender, EventArgs e) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrameProjectionDialog.cs:line 106
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at DotSpatial.Controls.MapFrame.Projection_Click(Object sender, EventArgs e) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapFrame.cs:line 1283
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.Control.WmCommand(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at RadioSpatial.Program.Main() in D:\Dev\dotNET\RadioSpatial_20-4-2011\RadioSpatial\RadioSpatial\Program.cs:line 20
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.Runtime.Hosting.ManifestRunner.Run(Boolean checkAptModel)
   at System.Runtime.Hosting.ManifestRunner.ExecuteAsAssembly()
   at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext, String[] activationCustomData)
   at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext)
   at System.Activator.CreateInstance(ActivationContext activationContext)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssemblyDebugInZone()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</code></pre>
InnerException:

**Comment by mogikanin** [comment]
Not reproduced
