### ISSUE TITLE
Unhandled ArgumentOutOfRangeException when loading a polygon shape file

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#326]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/333)**

**[jtrobbins](http://www.codeplex.com/site/users/view/jtrobbins)** wrote 2011-08-15 at 13:45
I was loading this test layer and got this exception 

System.ArgumentOutOfRangeException was unhandled 

Message=Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index 

Source=mscorlib 

ParamName=index 

StackTrace:

<pre><code>   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at DotSpatial.Data.PolygonShapefile.FillPolygons(String fileName, IProgressHandler progressHandler) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\PolygonShapefile.cs:line 286
   at DotSpatial.Data.PolygonShapefile.Open(String fileName, IProgressHandler progressHandler) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\PolygonShapefile.cs:line 86
   at DotSpatial.Data.Shapefile.OpenFile(String fileName, IProgressHandler progressHandler) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\Shapefile.cs:line 309
   at DotSpatial.Data.Shapefile.OpenFile(String fileName) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\Shapefile.cs:line 257
   at DotSpatial.Data.ShapefileDataProvider.Open(String fileName) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\ShapefileDataProvider.cs:line 74
   at DotSpatial.Data.ShapefileDataProvider.DotSpatial.Data.IDataProvider.Open(String fileName) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\ShapefileDataProvider.cs:line 79
   at DotSpatial.Data.DataManager.OpenFile(String fileName, Boolean inRam, IProgressHandler progressHandler) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\DataManager.cs:line 408
   at DotSpatial.Data.DataManager.OpenFile(String fileName) in C:\dev\DotSpatial\DotSpatial.Data\DotSpatial.Data\DataManager.cs:line 346
   at DotSpatial.Controls.MapLayerCollection.Add(String fileName) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\MapLayerCollection.cs:line 153
   at DotSpatial.Controls.Map.AddLayer(String fileName) in C:\dev\DotSpatial\DotSpatial.Controls\DotSpatial.Controls\Map.cs:line 571</code></pre>

**Comment by mogikanin** [comment]
Not reproduced.
