### ISSUE TITLE
Polygon Symbolizer Properties, change outline width causes Overflow Exception

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#327]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/334)**

**[jtrobbins](http://www.codeplex.com/site/users/view/jtrobbins)** wrote 2011-08-16 at 15:16
Edit a polygon symbol, in the outline section delete the width so it appears as a red area then enter a value.

at System.Drawing.Graphics.CheckErrorStatus(Int32 status) 

at System.Drawing.Graphics.DrawPath(Pen pen, GraphicsPath path) 

at DotSpatial.Symbology.LineSymbolizer.DrawPath(Graphics g, GraphicsPath gp, Double scaleWidth) in C:\Users\jasonr\Documents\Visual Studio 2010\Projects\Mobile\lib\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology\LineSymbolizer.cs:line 167

at DotSpatial.Symbology.Pattern.DrawPath(Graphics g, GraphicsPath gp, Double scaleWidth) in C:\Users\jasonr\Documents\Visual Studio 2010\Projects\Mobile\lib\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology\Pattern.cs:line 161

at DotSpatial.Symbology.Forms.PatternCollectionControl.lbxItems_DrawItem(Object sender, DrawItemEventArgs e) in C:\Users\jasonr\Documents\Visual Studio 2010\Projects\Mobile\lib\DotSpatial\DotSpatial.Symbology\DotSpatial.Symbology.Forms\PatternCollectionControl.cs:line
 112 

...

**Comment by mogikanin** [comment]
Not reproduced.
