### ISSUE TITLE
Error opening project with null values in attribute table

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#410]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/418)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2012-01-24 at 01:18
The following project "rc3.dspx" was created with DotSpatial RC3. 

When opening it, an unhandled exception is thrown in AttributeTable.cs line 1149 

{"Cannot parse at row 0, column 17 (SeriesID) in file searchresult_CZSNW.dbf using field type System.Double, and no DataTable to upgrade column"}

Stack Trace: 

J:\dev\DotSpatial\DotSpatial.Symbology\FeatureLayer.cs:line 1811 

at DotSpatial.Symbology.FeatureLayer.OnApplyScheme(IFeatureScheme scheme) in J:\dev\DotSpatial\DotSpatial.Symbology\FeatureLayer.cs:line 2020

at DotSpatial.Symbology.FeatureLayer.ApplyScheme(IFeatureScheme inScheme) in J:\dev\DotSpatial\DotSpatial.Symbology\FeatureLayer.cs:line 413

at DotSpatial.Symbology.FeatureLayer.set_Symbology(IFeatureScheme value) in J:\dev\DotSpatial\DotSpatial.Symbology\FeatureLayer.cs:line 1606

at DotSpatial.Symbology.PointLayer.set_Symbology(IPointScheme value) in J:\dev\DotSpatial\DotSpatial.Symbology\PointLayer.cs:line 152

This error doesn't occur when I create the same project using DotSpatial 1.0 RC2.

In the attachment: 

test_project_rc3.dspx - created with RC3, exception is thrown when opening with RC3, opens correctly with RC2.

test_project_rc2.dspx - created with RC2, exception is thrown when opening with RC3, opens correctly with RC2.

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2012-01-24 at 01:38
The exception only occurs if the category filter expression is in the format:

[ValueCount] > 1500 AND NOT ([SeriesID] is null)

If the expression is in the format:

[SeriesID] is null

then no exception occurs.

**Comment by mogikanin** [comment]
Not reproduced.
