### ISSUE TITLE
EntryPointNotFound error while symbolizing layer

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#57]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/61)**

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2010-09-28 at 18:34
Using the latest version from Codeplex (as of 9/28) on line 1202 of FeatureLayer.cs (IEnumerable<IFeatureCategory> categories = _scheme.GetCategories();) I get the error at the bottom of the post. I tried adding references to every DLL in DotSpatial
 but that didn't seem to help. The code to throw the error is: 

//add a layer to my map: 

IMapLayer stLyr = _mapArgs.Map.Layers.Add(fileName); 

if (stLyr != null)

<pre><code>            {
                MapPolygonLayer impl = (MapPolygonLayer)stLyr;
                //DIES HERE, impl is not null.
                impl.Symbolizer.SetFillColor(Color.BlanchedAlmond);
            }

</code></pre>
System.EntryPointNotFoundException was unhandled 

Message=Entry point was not found. 

Source=DotSpatial.Symbology 

TypeName="" 

StackTrace:

<pre><code>   at DotSpatial.Symbology.IFeatureScheme.GetCategories()
   at DotSpatial.Symbology.FeatureLayer.get_Symbolizer() in P:\Projects\AOR\DotSpatial\src\DotSpatial.Symbology\FeatureLayer.cs:line 1202
   at DotSpatial.Symbology.PolygonLayer.get_Symbolizer() in P:\Projects\AOR\DotSpatial\src\DotSpatial.Symbology\PolygonLayer.cs:line 162
</code></pre>
<em>CLIPPED FOR BREVITY</em>

**Comment by mogikanin** [comment]
Not actual
