### ISSUE TITLE
IDW fails to execute

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#717]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25843)**

**[BenWiseman](http://www.codeplex.com/site/users/view/BenWiseman)** wrote 2014-12-01 at 07:59
As the title says - IDW reliably fails. Currently the error message I'm getting is:

<blockquote>Error: DotSpatial.Topology.KDTree.KeySizeException: The size of the key did not match the size of the tree.

at DotSpatial.Topology.KDTree.KdTree.Search(Double[] key) in g:\TeamCity\buildAgent\work\356b083ef9ef62c7\DotSpatial.Topology\Index\KDTree\KDTree.cs:line 118

at DotSpatial.Tools.InverseDistanceWeighting.Execute(IFeatureSet input, String zField, Double cellSize, Double power, NeighborhoodType neighborType, Int32 pointCount, Double distance, IRaster output, ICancelProgressHandler cancelProgressHandler) in g:\TeamCity\buildAgent\work\356b083ef9ef62c7\DotSpatial.Tools\InverseDistanceWeighting.cs:line
 200

at DotSpatial.Tools.InverseDistanceWeighting.Execute(ICancelProgressHandler cancelProgressHandler) in g:\TeamCity\buildAgent\work\356b083ef9ef62c7\DotSpatial.Tools\InverseDistanceWeighting.cs:line 127

at DotSpatial.Controls.ToolManager.BwDoWork(Object sender, DoWorkEventArgs e) in g:\TeamCity\buildAgent\work\356b083ef9ef62c7\DotSpatial.Controls\ToolManager.cs:line 359

</blockquote>

**[mbayles](http://www.codeplex.com/site/users/view/mbayles)** wrote 2015-06-09 at 20:42
Are you able to post your code or files you are using?

**Comment by mogikanin** [comment]
Closing it since there is no response much time.
