### ISSUE TITLE
Accuracy of reprojection

### ISSUE THREAD

**Issue by JoshKeegan** [DotSpatial/DotSpatial#898]
Hi All,
I'm unsure if this is a bug or by design (as in the library isn't intended to be used for this), but I have used DotSpatial as part of a program to import shapefiles into a database and found a reprojection to be slightly inaccurate. 
During that import process, the data is reprojected to WGS84 with:
```cs
featureSet.Reproject(KnownCoordinateSystems.Geographic.World.WGS1984);
```
The original data is in the British National Grid (OSGB 1936), with the definition specified in the .prj files of the imported data:
```
PROJCS["British_National_Grid",GEOGCS["GCS_OSGB_1936",DATUM["D_OSGB_1936",SPHEROID["Airy_1830",6377563.396,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",400000.0],PARAMETER["False_Northing",-100000.0],PARAMETER["Central_Meridian",-2.0],PARAMETER["Scale_Factor",0.9996012717],PARAMETER["Latitude_Of_Origin",49.0],UNIT["Meter",1.0],AUTHORITY["EPSG",27700]]
```
At a glance the data appeared to be fine, but now when I have come to use it, I've found that it appears to be slightly out (not far, probably <100m although it varies depending on where I look at).  
  
As a sanity check, I loaded up a shapefile in QGIS and reprojected it to WGS84. Picking a random shape and checking the coordinates gives slightly different values to the ones from DotSpatial, with the QGIS ones appearing to be correct.  
  
Is this something I've done wrong with DotSpatial? Is there a more accurate reprojection method in the library I am unaware of?  
Or is the library not designed to give highly accurate projections and I need to consider an alternative?
Many thanks,
Josh Keegan

**Comment by jany-tenaj** [comment]
Which DotSpatial version are you using?

**Comment by JoshKeegan** [comment]
v1.9.0 off nuget

**Comment by jany-tenaj** [comment]
Please try the [latest binaries](https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master) from master branch. 
There were some fixes to projection issues. Maybe your issue was fixed, too.

**Comment by JoshKeegan** [comment]
I've just tried the latest binaries and got the same results as I did with v1.9.0.

**Comment by JoshKeegan** [comment]
Update:
The results have changed if with the latest binaries I add:
```cs
// Force BNG36 projection
featureSet.Projection = KnownCoordinateSystems.Projected.NationalGrids.BritishNationalGridOSGB36;
```
before the reprojection.  
I need to re-import all the data and see if it's actually correct, but the coordinates for the sample polygon i've been checking appear to be correct. You can see the difference this has made for a sample area with both lots of imported data overlayed:
![image](https://cloud.githubusercontent.com/assets/1682204/20973351/3d1a628e-bc90-11e6-8d8c-77ca07193bfb.png)

Setting the projection before reprojecting in the version of DotSpatial off of nuget doesn't work, throwing an exception when I later call `IFeature.ToShape()`:
```
System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=The IFeature.NumPoints of the parameter feature must be greater than 0.
Parameter name: feature
  ParamName=feature
  Source=DotSpatial.Data
  StackTrace:
       at DotSpatial.Data.Shape..ctor(IFeature feature)
       at DotSpatial.Data.Feature.ToShape()
       at ImportOsCodePointWithPolygons.Helpers.ShapeFileHelpers.<Load>d__0.MoveNext() in C:\Users\joshk\Documents\Visual Studio 2015\Projects\ImportOsCodePointWithPolygons\ImportOsCodePointWithPolygons\Helpers\ShapeFileHelpers.cs:line 49
       at ImportOsCodePointWithPolygons.Program.run() in C:\Users\joshk\Documents\Visual Studio 2015\Projects\ImportOsCodePointWithPolygons\ImportOsCodePointWithPolygons\Program.cs:line 64
       at ImportOsCodePointWithPolygons.Program.Main(String[] args) in C:\Users\joshk\Documents\Visual Studio 2015\Projects\ImportOsCodePointWithPolygons\ImportOsCodePointWithPolygons\Program.cs:line 46
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by JoshKeegan** [comment]
Alright, I can confirm all the data is imported and appears to be correct after forcing the original CRS to be OSGB  1936 (as above).

That's still just a workaround though. As far as I can tell the ESRI WKT in the .prj files (included in my original post) appears to be correct, so my assumption is that DotSpatial has parsed that incorrectly.

**Comment by jany-tenaj** [comment]
Can you attach the shapefile you used so we can use it to check this problem?

**Comment by JoshKeegan** [comment]
I'm unable to attach the full data here because the it's the Ordnance Survey: Code-Point with Polygons dataaset, which is proprietary.
However, they have a sample area available to download from https://www.ordnancesurvey.co.uk/docs/sample-data/code-point-polygons-shp-sample-data.zip#sample-data-download

That, combined with the content from the .prj file in my first post should be good to reproduce this. If not, let me know and I'll have to check what I can supply to help you without breaching our licence agreement.
