### ISSUE TITLE
parameter is incorrect

### ISSUE THREAD

**Issue by TasGrinder** [DotSpatial/DotSpatial#973]
1. Connect when Bluetooth is on. 
2. Start Device Detection

DotSpatial version: Current

If I turn my BlueTooth off there is no error. So its trying to connect to a bluetooth device but I'm getting no error other then System.ComponentModel.Win32Exception:'The parameter is incorrect'

Im assuming this is a device that is cached, but I can't remove it. I need to handle the error and move on. I don't really care if it can't connect to the bluetooth other then to telling me it can't instead of breaking the app. 

Any help please.

**Comment by TasGrinder** [comment]
I finally got a stack trace from getting the error from the appdomain.unhandledexception: 
   at DotSpatial.Positioning.BluetoothDevice.Refresh()
   at DotSpatial.Positioning.BluetoothDevice.get_Name()
   at DotSpatial.Positioning.Device.BeginDetection()
   at DotSpatial.Positioning.Devices.BeginBluetoothDetection()
   at DotSpatial.Positioning.Devices.DetectionThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by TasGrinder** [comment]
I would love a Devices.UnhandledException

**Comment by TasGrinder** [comment]
I download the source code and I'm getting -2147024809 error code in the refresh method. Is it ok if I just skip this error code.

**Comment by jrpdrummer** [comment]
I am getting a similar problem. For me, it occurs when the device resumes from sleep mode:

<Exception><ExceptionType>System.ComponentModel.Win32Exception, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>The parameter is incorrect</Message><StackTrace>   at DotSpatial.Positioning.BluetoothDevice.Refresh()
   at DotSpatial.Positioning.BluetoothDevice.get_Name()
   at DotSpatial.Positioning.Device.BeginDetection()
   at DotSpatial.Positioning.Devices.BeginBluetoothDetection()
   at DotSpatial.Positioning.Devices.DetectionThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at DotSpatial.Positioning.BluetoothDevice.Refresh()
   at DotSpatial.Positioning.BluetoothDevice.get_Name()
   at DotSpatial.Positioning.Device.BeginDetection()
   at DotSpatial.Positioning.Devices.BeginBluetoothDetection()
   at DotSpatial.Positioning.Devices.DetectionThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</ExceptionString><NativeErrorCode>80070057</NativeErrorCode></Exception>

**Comment by loni13** [comment]
I have the exactly same problem as TasGrinder. 
The application breaks, try/catch helps nothing.

Is there any solution?
